services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-standalone-lab3
    ports:
      - "5672:5672"
      - "15671:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq